import AvatarIcon from './view/avatar.js';
import NewNavMenu from './view/nav-menu.js';
import NewSort from './view/sort.js';
import NewFilms from './view/film-list.js';
import NewButtonShowMore from './view/button-show-more.js';
import NewFilmsRated from './view/films-rated.js';
import NewFilmsMostComment from './view/films-most-commented.js';
import { render } from './render.js';
import NewFilmsCatalog from './prisenter/films-prisenter.js';
import NewFilmsCatalogRated from './prisenter/rated-films-precenter.js';
import NewFilmsCatalogMostComment from './prisenter/most-comment-films-prisenter.js';
import NewFilmCardModel from './model/film-card-model.js';
import NewFilmPopup from './prisenter/popup-prisenter.js';
import NewComment from './model/film-coment-model.js';
const header = document.querySelector('.header');
const main = document.querySelector('.main');
const footer = document.querySelector('.footer');
const filmsCatalog = new NewFilmsCatalog();
const filmsCatalogRated = new NewFilmsCatalogRated();
const filmsCatalogMostComment = new NewFilmsCatalogMostComment();
const filmsCardModel = new NewFilmCardModel();
const filmPopup = new NewFilmPopup();
const filmComment = new NewComment();
render( new AvatarIcon (), header);
render( new NewNavMenu(), main);
render(new NewSort(), main);
render(new NewFilms(), main);
const filmsContainer = main.querySelector('.films-list__container');
filmsCatalog.init(filmsContainer, filmsCardModel);
const films = main.querySelector('.films');
render(new NewButtonShowMore, films);
render(new NewFilmsRated, films);
render(new NewFilmsMostComment, films);
const topRated = main.querySelector('.rated');
filmsCatalogRated.init(topRated, filmsCardModel);
const mostCommented = main.querySelector('.most_commented');
filmsCatalogMostComment.init(mostCommented, filmsCardModel);
filmPopup.init(footer, filmsCardModel, filmComment);

